services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_USER=quotes
      - MYSQL_PASSWORD=quotes
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ~/docker/volumes/mariadb_quotes:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
